validate:
  image: gramener/builderrors
  script: builderrors

deploy:
  stage: deploy
  script: deploy
  variables:
    SERVER: gramener.com
    URL: gramex-ui
    VERSION: static
    SETUP: npm install && npm run build
